server:
  port:9261

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          url: https://github.com/SHREYAS1009/config
          clone-on-start: true

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}